name: DVC Model Training Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  train-model:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mlops-project-3

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install scikit-learn mlflow pandas "dvc[s3]"

    - name: Pull data with DVC
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: dvc pull

    - name: Run training script
      run: python3 train.py